### PR TITLE
tidy and tweak 1

### PR DESCRIPTION
**Pull request by dcrossleyau**

### CODE REVIEW

**Review by MikeTaylor — APPROVED** [review]
Very helpful, thank you! I especially like that you fixed my misspelling of NWK's name!

**Comment by dcrossleyau** [comment]
s/NWK/BWK/
:-)

**Comment by MikeTaylor** [comment]
I don't get it.

**Comment by dcrossleyau** [comment]
See your comment just above that "...misspelling of **NWK**'s name". It is "Brian W. K..." so should be "BWK".

**Comment by MikeTaylor** [comment]
Haha! How lame of me!

-- Mike.

**Pull request merged**
